# Generated by Django 2.2.13 on 2023-08-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
